version: "3"
services:
  test:
    image: golang:1.19
    volumes:
      - ..:/code
    command: go test -v -race
    working_dir: /code/integration
    environment:
      - MQTT_HOSTS=emqx gmqtt hivemq hmq mosquitto vernemq

  emqx:
    image: emqx/emqx:4.2.5
  gmqtt:
    image: gmqtt/gmqttd:v0.2.2
  hivemq:
    image: hivemq/hivemq4:4.4.4
  hmq:
    image: habakke/hmq:2.0.57
  mosquitto:
    image: eclipse-mosquitto:1.6.12
  vernemq:
    image: vernemq/vernemq:1.10.4.1
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
