version: "3"
services:
  test:
    image: golang:1.20
    mem_limit: 500m
    volumes:
      - ..:/code
    command: go test -v -race
    working_dir: /code/integration
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      - MQTT_HOSTS=activemq emqx hivemq mosquitto rumqttd vernemq

  activemq:
    image: apache/activemq-artemis:2.39.0
    mem_limit: 500m
    # TCP "connection refused" error before HTTP service
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8161"]
      interval: 2s
      timeout: 1s
      retries: 10

  emqx:
    image: emqx/emqx:5.7.2
    mem_limit: 500m
  hivemq:
    image: hivemq/hivemq-ce:2024.7
    mem_limit: 2000m
  mosquitto:
    image: eclipse-mosquitto:1.6.15
    mem_limit: 500m
  rumqttd:
    image: bytebeamio/rumqttd:0.19.0
    mem_limit: 100m
  vernemq:
    image: vernemq/vernemq:1.13.0
    mem_limit: 1000m
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
