version: "3"
services:
  test:
    image: golang:1.20
    mem_limit: 500m
    volumes:
      - ..:/code
    command: go test -v -race
    working_dir: /code/integration
    environment:
      - MQTT_HOSTS=emqx hivemq mosquitto vernemq

  emqx:
    image: emqx/emqx:5.7.2
    mem_limit: 500m
  hivemq:
    image: hivemq/hivemq-ce:2024.7
    mem_limit: 2000m
  mosquitto:
    image: eclipse-mosquitto:1.6.15
    mem_limit: 500m
  vernemq:
    image: vernemq/vernemq:1.13.0
    mem_limit: 1000m
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
